name: Test collection
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  changelog:
    uses: ansible-network/github_actions/.github/workflows/changelog.yml@main
  sanity:
    uses: ansible-network/github_actions/.github/workflows/sanity.yml@main
  # openvswitch.openvswitch has no dependency on netcommon or utils
  # hence skipping unit-galaxy and unit-source
  all_green:
    if: ${{ always() }}
    needs:
    - changelog
    - sanity
    runs-on: ubuntu-latest
    steps:
    - run: >-
        python -c "assert set([
        '${{ needs.changelog.result }}',
        '${{ needs.sanity.result }}',
        '${{ needs.unit-galaxy.result }}',
        '${{ needs.unit-source.result }}'
        ]) == {'success'}"
